# Case_1
# Zhambaldorzhieva A., Ryaguzova D., Zaytseva D.
#
import turtle
turtle.speed(100)
def triangle(x, y, a, linecolor, color):
    '''
        Function, drawing square.
        :param x: upper left corner coordinate x
        :param y: upper left corner coordinate y
        :param a: side length of a square
        :return: None
    '''
    turtle.up()
    turtle.setposition(x, y)
    turtle.down()
    turtle.color(linecolor, color)
    turtle.begin_fill()
    hyp = a * 2 ** 0.5
    turtle.forward(a)
    turtle.left(135)
    turtle.forward(hyp)
    turtle.left(135)
    turtle.forward(a)
    turtle.end_fill()
    turtle.left(90)
    turtle.up()

def paral(x,y,a):
    turtle.up()
    turtle.setposition(x, y)
    turtle.down()
    turtle.color('dark blue')
    turtle.begin_fill()
    turtle.forward(a / 2)
    turtle.left(135)
    turtle.forward((a/2)*2**0.5)
    turtle.left(45)
    turtle.forward(a / 2)
    turtle.left(135)
    turtle.forward((a/2)*2**0.55)
    turtle.left(45)
    turtle.end_fill()
    turtle.up()


def square(x, y, a):
    turtle.up()
    turtle.setposition(x, y)
    turtle.down()
    turtle.color('yellow', 'yellow')
    turtle.begin_fill()
    turtle.forward(a)
    turtle.right(90)
    turtle.forward(a)
    turtle.right(90)
    turtle.forward(a)
    turtle.right(90)
    turtle.forward(a)
    turtle.right(90)
    turtle.end_fill()
    turtle.up()

def main():
    '''
    Main function.
    :return: None
    '''
    triangle(0, 0, 150, 'pink', 'pink')
    turtle.left(90)
    triangle(0, 0, 150, 'blue', 'blue')
    turtle.right(90)
    square(0, 0, 150 // 2)
    turtle.forward(150 // 2)
    turtle.right(90)
    triangle(150 // 2, 0, 150 // 2, 'orange', 'orange')
    turtle.right(90)
    turtle.forward(150 // 2)
    triangle(0, 0, 150 // 2, 'green', 'green')
    turtle.forward(150 // 2)
    paral(-150 // 2, 0, 150)
    turtle.forward(150 // 2)
    turtle.left(135)
    turtle.forward(2 * (150 / 2) * 2 ** 0.5)
    turtle.left(90)
    triangle(0, -150, (150 / 2) * 2 ** 0.5, 'red', 'red')
#утка и ракета
    turtle.right(45)
    turtle.forward(150)
    turtle.forward(300)
    turtle.left(90)
    square(200,0,50)
    turtle.forward(50)
    turtle.right(180)
    turtle.forward(50)
    triangle(250, 50, 50, 'blue', 'blue')
    turtle.forward(50)
    triangle(200,0,50, 'orange', 'orange')
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    paral(300,0,100)
    turtle.left(180)
    triangle(300,0, 100, 'red', 'red')
    turtle.forward(100)
    turtle.right(90)
    square(300,(-100),50)
    turtle.right(90)
    turtle.forward(50)
    triangle(300, (-50 ),50, 'pink', 'pink')
    turtle.forward(200)
    turtle.right(45)
    paral(300,200,100)
    turtle.left(135)
    triangle(300,200,75,'purple','purple')
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    paral(300,125,75)
    turtle.left(180)
    turtle.forward(75)
    turtle.right(90)
    triangle(225, 125, 75, 'purple', 'purple')
    turtle.right(90)
    triangle(225,125,75, 'pink', 'pink')
    turtle.left(180)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(75)
    turtle.right(90)
    square(150,275,75)
    turtle.right(90)
    turtle.forward(75)
    triangle(150,200,75,'orange','orange')
    turtle.right(90)
    triangle(150,200,75,'red', 'red')

    turtle.done()
main()